/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apkmeasurer.view;

import apkmeasurer.other.ArrayOpcode;
import apkmeasurer.other.Data;
import apkmeasurer.other.Gram;
import apkmeasurer.other.Kgram;
import apkmeasurer.other.tableResultModel;
import brut.common.BrutException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zword
 */
public class MainFrame extends javax.swing.JFrame {
  
    File fileApk1;
    File fileApk2;
    String[] command = new String[4];
    
    String user = System.getProperty("user.name"); 
    
    FileNameExtensionFilter filter = new FileNameExtensionFilter("APK Files", "apk", "apk");
    
    List<File> fileList1 ;
    List<File> fileList2 ;
    
    List<ArrayOpcode> arrOp1 ;
    List<ArrayOpcode> arrOp2 ;
    
    List<Kgram> listK6gram1 ;
    List<Kgram> listK6gram2 ;

    List<Kgram> listK7gram1 ;
    List<Kgram> listK7gram2 ;
    
    List<Kgram> listK8gram1 ;
    List<Kgram> listK8gram2 ;
    
    List<tableResultModel> resultModel;
    DefaultTableModel dtm  = new DefaultTableModel();
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setTitle("Pengukur Kesamaan Aplikasi Android");
        command[0] = "d";
        command[2] = "-o";
//        command[3] = "/home/zulfikar/apkmeasurer";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        apk1Button = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        apk2Button = new javax.swing.JButton();
        buttonProcess = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        p1NameField = new javax.swing.JTextField();
        p1SizeField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        p2NameField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        p2SizeField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textResult = new javax.swing.JEditorPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        k6Field = new javax.swing.JTextField();
        k7Field = new javax.swing.JTextField();
        k8Field = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resulTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("File Apk 1 :");

        jLabel2.setText("File Apk 2 :");

        apk1Button.setText("Browse");
        apk1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apk1ButtonActionPerformed(evt);
            }
        });

        apk2Button.setText("Browse");
        apk2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apk2ButtonActionPerformed(evt);
            }
        });

        buttonProcess.setText("Process");
        buttonProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apk1Button)
                            .addComponent(apk2Button)))
                    .addComponent(buttonProcess))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apk1Button))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apk2Button))
                .addGap(26, 26, 26)
                .addComponent(buttonProcess)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Program 1");

        jLabel4.setText("Name");

        jLabel5.setText("Size");

        p1NameField.setEditable(false);

        p1SizeField.setEditable(false);

        jLabel6.setText("Name");

        jLabel7.setText("Size");

        p2NameField.setEditable(false);

        jLabel8.setText("Program 2");

        p2SizeField.setEditable(false);

        jLabel13.setText("Result");

        jLabel14.setText("Kb");

        jLabel15.setText("Kb");

        jScrollPane3.setViewportView(textResult);

        jLabel9.setText("k = 6");

        jLabel10.setText("k = 7");

        jLabel11.setText("k = 8");

        k6Field.setEditable(false);

        k7Field.setEditable(false);

        k8Field.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p1NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(p1SizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p2NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(p2SizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15)))))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(k6Field, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(k7Field, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(6, 6, 6)
                                .addComponent(k8Field, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(k6Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(k7Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(k8Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(p1NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(p1SizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)
                                .addComponent(jLabel13))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(p2NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(p2SizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))
                        .addGap(43, 43, 43))))
        );

        jLabel12.setText("Table kesamaan file");

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        resulTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "File apk1", "File apk2", "gram sama"
            }
        ));
        jScrollPane1.setViewportView(resulTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(clearButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apk1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apk1ButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        
        chooser.setFileFilter(filter);
        int returnval = chooser.showOpenDialog(null);
        if(returnval == JFileChooser.APPROVE_OPTION){
            fileApk1 = chooser.getSelectedFile();
            String filename = fileApk1.getAbsolutePath();
            jTextField2.setText(filename);
        }
        
    }//GEN-LAST:event_apk1ButtonActionPerformed

    private void apk2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apk2ButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(filter);
        int returnval = chooser.showOpenDialog(null);
        if(returnval == JFileChooser.APPROVE_OPTION){
            fileApk2 = chooser.getSelectedFile();
            String filename = fileApk2.getAbsolutePath();
            jTextField3.setText(filename);
        }
    }//GEN-LAST:event_apk2ButtonActionPerformed

//    PROCCESS START HERE
    private void buttonProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcessActionPerformed
        // TODO add your handling code here:
//        logTextArea.setText("");
        textResult.setText("");
        System.out.println("Text Clear");
        buttonProcess.setEnabled(false);
        
        resultModel = new ArrayList<tableResultModel>();
        
        try {
            // TODO add your handling code here:
            executeApkTool(fileApk1.getAbsolutePath(),fileApk2.getAbsolutePath());
            float containment6,containment7,containment8 , containment;
            try {
                gramProcess();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
//            writeLog("Measure K 6");
            System.out.println("Measure K 6");
            float k6temp = (float)measureKgram(listK6gram1,listK6gram2);
            float k6temp2 = (float)totalGram(listK6gram1);
            containment6 = k6temp/k6temp2;

//            writeLog("Measure K 7");
            System.out.println("Measure K 7");
            float k7temp = (float)measureKgram(listK7gram1,listK7gram2);
            float k7temp2 = (float)totalGram(listK7gram1);
            containment7 = k7temp/k7temp2;

//            writeLog("Measure K 8");
            System.out.println("Measure K 8");
            float k8temp = (float)measureKgram(listK8gram1,listK8gram2);
            float k8temp2 = (float)totalGram(listK8gram1);
            containment8 = k8temp/k8temp2;

            System.out.println("Total measure k6 = "+k6temp);
            System.out.println("Total gram1 k6 = "+k6temp2);
            System.out.println("containement k6 = "+containment6*100+" %");
            System.out.println("");


            System.out.println("Total measure k7= "+k7temp);
            System.out.println("Total gram1 k7= "+k7temp2);
            System.out.println("containement k7= "+containment7*100+" %");
            System.out.println("");


            System.out.println("Total measure k8= "+k8temp);
            System.out.println("Total gram1 k8= "+k8temp2);
            System.out.println("containement k8= "+containment8*100+" %");
            System.out.println("");

            String nameFile1 = fileApk1.getName();
            String nameFile2 = fileApk2.getName();
            String sizeFile1 = Double.toString(fileApk1.length()/1024);
            String sizeFile2= Double.toString(fileApk2.length()/1024);

            p1NameField.setText(nameFile1);
            p1SizeField.setText(sizeFile1);

            p2NameField.setText(nameFile2);
            p2SizeField.setText(sizeFile2);
            
            NumberFormat formatter = new DecimalFormat("#0.00");
            
            String finalK;
            String mirip ;
            String kesimpulan ;
            
            if((containment6 > containment7) && (containment6 > containment8)){
                finalK = "6";
                containment = containment6;
            }else if((containment7 > containment6) && (containment7 > containment8)){
                finalK = "7";
                containment = containment7;
            }else{
                finalK = "8";
                containment = containment8;
            }
            
            if(containment > 0.5){
                mirip = "lebih besar";
                kesimpulan = "mirip dengan "+nameFile2+"";
            }else if(containment < 0.5){
                mirip = "lebih kecil";
                kesimpulan = "tidak mirip dengan "+nameFile2+"";
            }else{
                mirip = "sama";
                kesimpulan = "masih meragukan";
            }
            textResult.setContentType("text/html");
            
            String result = "Berdasarkan perhitungan dengan metode k-gram maka <b>"+nameFile1+"</b> \n"
                    + "mempunyai tingkat kemiripan sebesar <b>"+formatter.format(containment*100)+"%</b> dari <b>"+nameFile2+"</b> \n"
                    + "yang didapat dari k sebesar <b> "+finalK+" </b> dari nilai max antara k 6 7 dan 8\n"
                    + "Karena tingkat kemiripan <b>"+mirip+"</b> dari tingkat tidak miripnya sehingga bisa \n"
                    + "disimpulkan bahwa <b>"+nameFile1+" "+kesimpulan+"</b>";
            
            textResult.setText(result);
            
            k6Field.setText(formatter.format(containment6*100));   
            k7Field.setText(formatter.format(containment7*100));
            k8Field.setText(formatter.format(containment8*100));
            
            dtm = new DefaultTableModel(new Object[][]{},new String[]{"File Apk1","File Apk2","Gram sama"});
            for(tableResultModel p:resultModel){
            dtm.addRow(new Object[]{p.getNameApk1(),p.getNameApk2(),p.getSimilarity()});
            }
            resulTable.setModel(dtm);

    //        tableResult.setValueAt("Title1",0,0);
    //        tableResult.setValueAt("Size1",0,1);
    //        tableResult.setValueAt(containment6,0,2);
    //        tableResult.setValueAt(containment7,0,3);
    //        tableResult.setValueAt(containment8,0,4);
    //        
    //        tableResult.setValueAt("Title2",1,0);
    //        tableResult.setValueAt("Size2",1,1);
    //        tableResult.setValueAt("k6gram2",1,2);
    //        tableResult.setValueAt("k7gram2",1,3);
    //        tableResult.setValueAt("k8gram2",1,4);
            
        }catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Inputan APK masih kosong!!");
            
        } catch (IOException ex) {
            System.out.println("IOException");
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            System.out.println("InterruptedException");
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BrutException ex) {
            System.out.println("BrutException");
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        buttonProcess.setEnabled(true);
        
    }//GEN-LAST:event_buttonProcessActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
//        logTextArea.setText("");
        dtm.setRowCount(0);
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }
    
    public void executeApkTool(String path1 , String path2) throws IOException, InterruptedException, BrutException{
        int containment;
        deleteFile();
//        buttonDissasemble.setEnabled(false);
        command[1] = path1;
        command[3] = "/home/"+user+"/Apkmeasurer/subject1";
       
        brut.apktool.Main.main(command);
        
        
        command[1] = path2;
        command[3] = "/home/"+user+"/Apkmeasurer/subject2";
        
        
        
        brut.apktool.Main.main(command);
//        buttonDissasemble.setEnabled(true);
//        writeLog("Dissassemble done");
        System.out.println("Dissassemble done");
        
//        gramProcess();
//        containment = measureKgram(listK6gram1,listK6gram2)/totalGram(listK6gram1);
//        System.out.println("Result");
//        System.out.println(containment);
    }
    
    
    private void gramProcess() throws FileNotFoundException{
        fileList1 = new ArrayList<File>();
        fileList2 = new ArrayList<File>();
        
        arrOp1 = new ArrayList<ArrayOpcode>();
        arrOp2 = new ArrayList<ArrayOpcode>();
        
        listK6gram1 = new ArrayList<Kgram>();
        listK6gram2 = new ArrayList<Kgram>();

        listK7gram1 = new ArrayList<Kgram>();
        listK7gram2 = new ArrayList<Kgram>();
    
        listK8gram1 = new ArrayList<Kgram>();
        listK8gram2 = new ArrayList<Kgram>();
        
//        writeLog("Listing subject 1");
        listingFile("/home/"+user+"/Apkmeasurer/subject1",fileList1);
//        writeLog("Listing subject 2");
        listingFile("/home/"+user+"/Apkmeasurer/subject2",fileList2);
        
        int count=0;
        
         for (File file : fileList1){
             count++;
             //Make array Opcode
             ArrayOpcode arr = new ArrayOpcode(file);
             
             //Insert to arrayList
             arrOp1.add(arr);
         }
         
         System.out.println("File= "+count);

         
         for (File file : fileList2){
             ArrayOpcode arr = new ArrayOpcode(file);
             arrOp2.add(arr);
         }
         
         for(ArrayOpcode array:arrOp1){
             Kgram kgram = new Kgram(array,6);
             listK6gram1.add(kgram);
         }
         
         for(ArrayOpcode array:arrOp2){
             Kgram kgram = new Kgram(array,6);
             listK6gram2.add(kgram);
         }
         
         for(ArrayOpcode array:arrOp1){
             Kgram kgram = new Kgram(array,7);
             listK7gram1.add(kgram);
         }
         
         for(ArrayOpcode array:arrOp2){
             Kgram kgram = new Kgram(array,7);
             listK7gram2.add(kgram);
         }
         
         for(ArrayOpcode array:arrOp1){
             Kgram kgram = new Kgram(array,8);
             listK8gram1.add(kgram);
         }
         
         for(ArrayOpcode array:arrOp2){
             Kgram kgram = new Kgram(array,8);
             listK8gram2.add(kgram);
         }
    }
    
    private int measureKgram(List<Kgram> listKgram1,List<Kgram> listKgram2){
//        System.out.println("Measure Kgram");
//        System.out.println(totalGram(listKgram1));
//        System.out.println(totalGram(listKgram2));
//        stack here
        int count=0;
        int lebih=0;
        String name="";
        for(Kgram kgram1:listKgram1){
            
            int max=0;
            
//            System.out.println("core "+kgram1.arrOp.getName());
            for(Kgram kgram2:listKgram2){
                int temp = countSimilar(kgram1,kgram2);
//                System.out.println("");
//                System.out.println("temp "+temp);
//                System.out.println("name "+kgram2.arrOp.getName());
//                System.out.println("");
                //wrong get max
                if(max<temp){
                    max = temp;
                    name = kgram2.arrOp.getName();
                }
      
            }
//            System.out.println(kgram1.arrOp.getName());
//            System.out.println(name);
//            System.out.println("kgram1= "+kgram1.getGramCount());
//            System.out.println("max= "+max);
//            System.out.println("");
            if(max != 0){
                System.out.println(kgram1.getName()+" most similar "+name+" with similarity "+max);
//                  writeLog(kgram1.getName()+" most similar "+name+" with similarity "+max);
                resultModel.add(new tableResultModel(kgram1.getName(), name, max));

            }
            count += max;
        }
        return count;
    }
    
    private int countSimilar(Kgram kgram1,Kgram kgram2){
        
//        problem with copy / use clone if desperate
//        solution using copy constructer or find way
//        to not counting same object in arraylist
        int count=0;
        int hitung;
        boolean flag;
        List<Integer> tampung = new ArrayList<Integer>();
        Kgram temp ;
        for(Gram gram1:kgram1.getKgram()){
            temp = kgram2;      
            hitung = 0;
            
            for(Gram gram2:temp.getKgram()){
                flag=false;
                hitung++;
                
                for(Integer a:tampung){
                    if(a==hitung){
                        flag=true;
                    }
                }
                
                if(flag){
                    continue;
                }
                
                if(gram1.equals(gram2)){
                   count++;
                   tampung.add(hitung);
                   break;
                }
            }
               
        }
        return count;
    }
    
    private boolean isGramEqual(Gram gram1,Gram gram2){
        return gram1.equals(gram2);
    }
    
    private int totalGram(List<Kgram> listKgram){
        int count=0;
        for(Kgram kgram:listKgram){
            count+=kgram.getGramCount();
        }
        return count;
    }
    
//    Memasukkan semua file kedalam List
    private void listingFile(String directoryName,List<File> fileList){
        File directory = new File(directoryName);
        

    // get all the files from a directory
        File[] fList = directory.listFiles();

        for (File file : fList) {
            if (file.isFile()) {
                if(file.getName().endsWith(".smali")) {
                    fileList.add(file);
                }
            } else if (file.isDirectory()) {
                int flag = 0;
                for(int i= 0 ; i< Data.library.length;i++){
                    if(file.getName().equals(Data.library[i])){
                        System.out.println(file.getName());
                        flag = 1;
                    }
                }
                if(flag == 1){
              
                }else{
                    listingFile(file.getAbsolutePath(),fileList);          
                }
                
                
//                if(file.getName().equals("android")){
//                    System.out.println(file.getName());
//                }else{
//                    listingFile(file.getAbsolutePath(),fileList);
//                    
//                }
                
            }
        }
    }
    
//    private void writeLog(String text){
//        System.out.println(text);
//        String currentLog = logTextArea.getText();
//        if(logTextArea.equals("")){
//            logTextArea.setText(text);
//        }else{
//            logTextArea.setText(currentLog+"\n"+text);
//        }
//        
//        
//        
//    }
    
    private void deleteFile(){
        System.out.println("delete File");
         try {
            String line;
            Process p = Runtime.getRuntime().exec("rm -rf /home/"+user+"/Apkmeasurer");
             BufferedReader bri =
            new BufferedReader(new InputStreamReader(p.getInputStream()));
            BufferedReader bre =
            new BufferedReader(new InputStreamReader(p.getErrorStream()));
            while ((line = bri.readLine()) != null) {
            // System.out.println("input...");
            System.out.println(line);
            }
            bri.close();
            while ((line = bre.readLine()) != null) {
            System.out.println("error...");
            System.out.println(line);
            }
            bre.close();
            p.waitFor();
            System.out.println("Done.");
            }
            catch (Exception err) {
            err.printStackTrace();
            }
    }
    
    
    
//    public void createTempDir1(){
//        File temp1 = new File("/home/"+System.getProperty("user.name")+"/.apk_measure//apk1/");
//        
//        if (!temp1.exists()) {
//		if (temp1.mkdirs()) {
//			System.out.println("temp1 is created!");
//                        
//		} else {
//			System.out.println("Failed to create temp1!");
//		}
//	}
//        File temp2 = new File("/home/"+System.getProperty("user.name")+"/.apk_measure//apk2/");
//        if (!temp2.exists()) {
//		if (temp2.mkdirs()) {
//			System.out.println("temp2 is created!");
//                        
//		} else {
//			System.out.println("Failed to create temp2!");
//		}
//	}
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apk1Button;
    private javax.swing.JButton apk2Button;
    private javax.swing.JButton buttonProcess;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField k6Field;
    private javax.swing.JTextField k7Field;
    private javax.swing.JTextField k8Field;
    private javax.swing.JTextField p1NameField;
    private javax.swing.JTextField p1SizeField;
    private javax.swing.JTextField p2NameField;
    private javax.swing.JTextField p2SizeField;
    private javax.swing.JTable resulTable;
    private javax.swing.JEditorPane textResult;
    // End of variables declaration//GEN-END:variables
}
